
lights:
  # - name: boomtone
  #   channel: 1
  #   fixture: Fixtures/boomtonepartypar123.yaml
  # - name: bigpar
  #   channel: 1 #17
  #   fixture: Fixtures/bigpar27rgbw.yaml
  # - name: uv
  #   fixture: Fixtures/extraflatparcanuv.yaml
  #   channel: 7
  - name: irled
    fixture: Fixtures/irled64.yaml
    channel: 3

layout:
  components:
  # - group: all colors
  #   components:
  #   - uv
  #   - irled
  #   - bigpar
  #   - boomtone
  # - light: bigpar
  # - light: boomtone
  # - light: uv
  - light: irled
